on:
 
  push:
    branches: [ master ]
  pull_request:
  
    branches: [ master ]
    types: [opened, reopened]



  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: ./
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            Pull request is opened.
            ${{ github.event.number }}: ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.html_url }}
