# This is a basic workflow to help you get started with Actions

name: Notify pull request


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  notify:


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: 'some message'


